# Generated by Django 5.1.5 on 2025-01-23 20:41

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', cloudinary.models.CloudinaryField(default='images/accessories-bag', max_length=255, verbose_name='image')),
                ('theme_song', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio')),
                ('experience', models.CharField(choices=[('Wanderer', 'Wanderer'), ('Pathfinder', 'Pathfinder'), ('Explorer', 'Explorer'), ('Cultural Ambassador', 'Cultural Ambassador'), ('World Voyager', 'World Voyager'), ('Global Legend', 'Global Legend')], max_length=55)),
                ('status', models.TextField(blank=True, max_length=255)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visited_countries', models.ManyToManyField(blank=True, to='profiles.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
