# Generated by Django 5.1.5 on 2025-01-26 19:05

import cloudinary.models
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', cloudinary.models.CloudinaryField(default='pexels-nurseryart-346885_nj7aji', max_length=255, verbose_name='image')),
                ('theme_song', cloudinary.models.CloudinaryField(default='travel-audio-oficial-243586_eehcqv', max_length=255, verbose_name='audio')),
                ('experience', models.CharField(choices=[('Wanderer', 'Wanderer'), ('Pathfinder', 'Pathfinder'), ('Explorer', 'Explorer'), ('Cultural Ambassador', 'Cultural Ambassador'), ('World Voyager', 'World Voyager'), ('Global Legend', 'Global Legend')], max_length=55)),
                ('visited_countries', django_countries.fields.CountryField(blank=True, max_length=746, multiple=True)),
                ('status', models.TextField(blank=True, max_length=255)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
