# Generated by Django 5.1.5 on 2025-01-30 14:01

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visited_countries',
            field=django_countries.fields.CountryField(blank=True, default='list', max_length=746, multiple=True),
        ),
    ]
