# Generated by Django 5.1.5 on 2025-01-23 20:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='pexels-nurseryart-346885_nj7aji', max_length=255, verbose_name='image'),
        ),
    ]
