# Generated by Django 5.1.5 on 2025-01-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_visited_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(choices=[('Wanderer', 'Wanderer'), ('Pathfinder', 'Pathfinder'), ('Explorer', 'Explorer'), ('Cultural Ambassador', 'Cultural Ambassador'), ('World Voyager', 'World Voyager'), ('Global Legend', 'Global Legend')], default='Wanderer', max_length=55),
        ),
    ]
