# Generated by Django 5.1.5 on 2025-01-23 21:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme_song',
            field=cloudinary.models.CloudinaryField(default='travel-audio-oficial-243586_eehcqv', max_length=255, verbose_name='audio'),
        ),
    ]
