# Generated by Django 5.1.5 on 2025-01-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('profiles', '0005_alter_profile_theme_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterField(
            model_name='profile',
            name='visited_countries',
            field=models.ManyToManyField(blank=True, to='countries.country'),
        ),
    ]
