# Generated by Django 4.2.19 on 2025-03-30 20:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_profile_ktgpxq', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme_song',
            field=cloudinary.models.CloudinaryField(default='travel-audio-oficial-243586_eehcqv.mp3', max_length=255, verbose_name='audio'),
        ),
    ]
