# Generated by Django 5.1.5 on 2025-01-31 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_preference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelpreference',
            old_name='preferred_continents',
            new_name='preferred_continent',
        ),
        migrations.RemoveField(
            model_name='travelpreference',
            name='preferred_countries',
        ),
    ]
