# Generated by Django 4.2.19 on 2025-02-26 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_preference', '0002_rename_preferred_continents_travelpreference_preferred_continent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpreference',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
