# Generated by Django 4.2.19 on 2025-04-01 12:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='accessories-bag', max_length=255, verbose_name='image'),
        ),
    ]
