# Generated by Django 5.1.5 on 2025-02-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrecommendation',
            name='recommended_destination',
            field=models.JSONField(default=list, blank=True, null=True),
        ),
    ]
