# Generated by Django 5.1.5 on 2025-02-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_recommendation', '0002_alter_travelrecommendation_recommended_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrecommendation',
            name='recommended_destination',
            field=models.JSONField(default=list),
        ),
    ]
