# Generated by Django 5.1.5 on 2025-01-26 13:23

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
