# Generated by Django 5.1.5 on 2025-01-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbuddy',
            name='confirmed_by_buddy',
            field=models.BooleanField(default=False),
        ),
    ]
