# Generated by Django 5.1.5 on 2025-01-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0002_travelbuddy_confirmed_by_buddy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelbuddy',
            old_name='confirmed',
            new_name='buddy',
        ),
        migrations.RemoveField(
            model_name='travelbuddy',
            name='confirmed_by_buddy',
        ),
    ]
