# Generated by Django 5.1.5 on 2025-01-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0003_rename_confirmed_travelbuddy_buddy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelbuddy',
            options={'ordering': ['-requested_at']},
        ),
        migrations.RenameField(
            model_name='travelbuddy',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RemoveField(
            model_name='travelbuddy',
            name='buddy',
        ),
        migrations.AddField(
            model_name='travelbuddy',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelbuddy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
